Add inital support for a tab drag window.
Igalia/chromium pull request #432
Opened 2018-05-14 10:35 UTC by jkim-julie

There are 3 changes comparing to previous change.
1) Removed changes at services.
2) Added GetLocalProcessWindowAtPointOzone to support tab dragging without mus on ozone.
It's similar to GetLocalProcessWindowAtPointMus.
3) Added body at RunMoveLoop/EndMoveLoop from DesktopWindowTreeHostPlatform.
PTAL.

2018-05-15 09:56 UTC, msisov commented
please rebase.

2018-05-16 07:22 UTC, msisov requested changes

2018-05-16 07:22 UTC, msisov commented on ui/platform_window/platform_window.h
> +  virtual bool RunMoveLoop(const gfx::Vector2d& drag_offset) = 0;
would you please implement this for ui/ozone/platform/cast as well? AFAIK, it also implement platform_window.h

2018-05-16 08:26 UTC, jkim-julie commented on ui/platform_window/platform_window.h
> +  virtual bool RunMoveLoop(const gfx::Vector2d& drag_offset) = 0;
Updated.

2018-05-16 08:28 UTC, merged